environment: test
elastic:
    url: ""
    auth:
        username: ""
        password: ""
kafka:
    brokers:
        - ""
        - ""
        - ""
    version: ""
    group: ""
    topics:
        - ""
    assignor: ""
    oldest: true
    verbose: false
    Topic: ""
    username: ""
    password: ""

twitter:
    consumerKey: ""
    consumerSecret: ""
    accessToken: ""
    accessTokenSecret: ""